apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: product-app
  labels:
    app: product-app
    component: spring-boot
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: product-app
    component: spring-boot
